// <auto-generated />
using System;
using ComplaintsAPI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComplaintsAPI.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413132351_AddComplaintPerformanceIndexes")]
    partial class AddComplaintPerformanceIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.Complaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcodes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ComplaintDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ComplaintMonth")
                        .HasColumnType("int");

                    b.Property<string>("ComplaintNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ComplaintWeek")
                        .HasColumnType("int");

                    b.Property<int>("ComplaintYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int>("CurrentDepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CustomerFeedbackAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerFeedbackById")
                        .HasColumnType("int");

                    b.Property<string>("CustomerFeedbackNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DefectiveQuantity")
                        .HasColumnType("int");

                    b.Property<string>("ErrorDefinition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Has8DReport")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasTargetDate")
                        .HasColumnType("bit");

                    b.Property<int?>("Hsa1")
                        .HasColumnType("int");

                    b.Property<int?>("Hsa2")
                        .HasColumnType("int");

                    b.Property<string>("InitialNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCustomerFeedbackDone")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsManagementApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsQualityReported")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsValidComplaint")
                        .HasColumnType("bit");

                    b.Property<int>("JustifiedHsa1Count")
                        .HasColumnType("int");

                    b.Property<int>("JustifiedHsa2Count")
                        .HasColumnType("int");

                    b.Property<int>("JustifiedOtherCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManagementApprovalNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagementApprovedById")
                        .HasColumnType("int");

                    b.Property<string>("ModulePower")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OperationalStage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("QualityReportNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QualityReportedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Acik");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnjustifiedHsa1Count")
                        .HasColumnType("int");

                    b.Property<int>("UnjustifiedHsa2Count")
                        .HasColumnType("int");

                    b.Property<int>("UnjustifiedOtherCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Brand");

                    b.HasIndex("ComplaintDate");

                    b.HasIndex("ComplaintNumber")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CurrentDepartmentId");

                    b.HasIndex("CustomerFeedbackById");

                    b.HasIndex("ManagementApprovedById");

                    b.HasIndex("QualityReportedById");

                    b.HasIndex("RegistrationDate");

                    b.HasIndex("Status");

                    b.HasIndex("ComplaintDate", "Brand");

                    b.HasIndex("CurrentDepartmentId", "Status");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.ComplaintBarcodeResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ComplaintId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsJustified")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintId");

                    b.ToTable("ComplaintBarcodeResults");
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.ComplaintDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComplaintId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Is8DReport")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedAtStage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UploadedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintId");

                    b.HasIndex("UploadedById");

                    b.ToTable("ComplaintDocuments");
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.ComplaintHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedById")
                        .HasColumnType("int");

                    b.Property<int>("ComplaintId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FromStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("ComplaintId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("ComplaintHistories");
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Satış"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kalite"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kalite Güvence"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Yönetim"
                        },
                        new
                        {
                            Id = 5,
                            Name = "IT"
                        });
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.ErrorDefinitionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ErrorDefinitionOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Busbar Lehim Hatası"
                        },
                        new
                        {
                            Id = 2,
                            Label = "Cam Çiziği"
                        },
                        new
                        {
                            Id = 3,
                            Label = "Cam Kirliliği"
                        },
                        new
                        {
                            Id = 4,
                            Label = "Çerçeve Köşe Açıklığı"
                        },
                        new
                        {
                            Id = 5,
                            Label = "Diyot Hatası"
                        },
                        new
                        {
                            Id = 6,
                            Label = "EL hatası"
                        },
                        new
                        {
                            Id = 7,
                            Label = "Etiket Hatası"
                        },
                        new
                        {
                            Id = 8,
                            Label = "EVA Lekesi"
                        },
                        new
                        {
                            Id = 9,
                            Label = "Finger Kırığı"
                        },
                        new
                        {
                            Id = 10,
                            Label = "Gökkuşağı"
                        },
                        new
                        {
                            Id = 11,
                            Label = "Güç Hatası"
                        });
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.ProductionCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month")
                        .IsUnique();

                    b.ToTable("ProductionCounts");
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 13, 6, 54, 53, 504, DateTimeKind.Utc).AddTicks(1966),
                            DepartmentId = 5,
                            Email = "admin@sirket.com",
                            IsDeleted = false,
                            Name = "Sistem Yöneticisi",
                            PasswordHash = "$2a$11$P3kNTepbQzw8ZluWSL4GyuF44YonfQkVEGdBdpjL7IQoS9EUwuzBa",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.UserActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserFullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserActivityLogs");
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.Complaint", b =>
                {
                    b.HasOne("ComplaintsAPI.Domain.Entities.User", "CreatedBy")
                        .WithMany("CreatedComplaints")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComplaintsAPI.Domain.Entities.Department", "CurrentDepartment")
                        .WithMany("Complaints")
                        .HasForeignKey("CurrentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComplaintsAPI.Domain.Entities.User", "CustomerFeedbackBy")
                        .WithMany()
                        .HasForeignKey("CustomerFeedbackById");

                    b.HasOne("ComplaintsAPI.Domain.Entities.User", "ManagementApprovedBy")
                        .WithMany()
                        .HasForeignKey("ManagementApprovedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ComplaintsAPI.Domain.Entities.User", "QualityReportedBy")
                        .WithMany()
                        .HasForeignKey("QualityReportedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("CurrentDepartment");

                    b.Navigation("CustomerFeedbackBy");

                    b.Navigation("ManagementApprovedBy");

                    b.Navigation("QualityReportedBy");
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.ComplaintBarcodeResult", b =>
                {
                    b.HasOne("ComplaintsAPI.Domain.Entities.Complaint", "Complaint")
                        .WithMany("BarcodeResults")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.ComplaintDocument", b =>
                {
                    b.HasOne("ComplaintsAPI.Domain.Entities.Complaint", "Complaint")
                        .WithMany("Documents")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComplaintsAPI.Domain.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Complaint");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.ComplaintHistory", b =>
                {
                    b.HasOne("ComplaintsAPI.Domain.Entities.User", "ChangedBy")
                        .WithMany("ComplaintHistories")
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComplaintsAPI.Domain.Entities.Complaint", "Complaint")
                        .WithMany("History")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComplaintsAPI.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChangedBy");

                    b.Navigation("Complaint");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.User", b =>
                {
                    b.HasOne("ComplaintsAPI.Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.UserActivityLog", b =>
                {
                    b.HasOne("ComplaintsAPI.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.Complaint", b =>
                {
                    b.Navigation("BarcodeResults");

                    b.Navigation("Documents");

                    b.Navigation("History");
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.Department", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.User", b =>
                {
                    b.Navigation("ComplaintHistories");

                    b.Navigation("CreatedComplaints");
                });
#pragma warning restore 612, 618
        }
    }
}
