// <auto-generated />
using System;
using ComplaintsAPI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComplaintsAPI.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310115105_RenameAdminDepartmentToIT")]
    partial class RenameAdminDepartmentToIT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.Complaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcodes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ComplaintDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ComplaintMonth")
                        .HasColumnType("int");

                    b.Property<string>("ComplaintNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ComplaintWeek")
                        .HasColumnType("int");

                    b.Property<int>("ComplaintYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int>("CurrentDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DefectiveQuantity")
                        .HasColumnType("int");

                    b.Property<string>("ErrorDefinition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Hsa1")
                        .HasColumnType("int");

                    b.Property<int?>("Hsa2")
                        .HasColumnType("int");

                    b.Property<string>("InitialNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsManagementApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsQualityReported")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsValidComplaint")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManagementApprovalNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagementApprovedById")
                        .HasColumnType("int");

                    b.Property<string>("ModulePower")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("QualityReportNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QualityReportedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Acik");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CurrentDepartmentId");

                    b.HasIndex("ManagementApprovedById");

                    b.HasIndex("QualityReportedById");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.ComplaintHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedById")
                        .HasColumnType("int");

                    b.Property<int>("ComplaintId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FromStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("ComplaintId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("ComplaintHistories");
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Satış"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kalite"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kalite Güvence"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Yönetim"
                        },
                        new
                        {
                            Id = 5,
                            Name = "IT"
                        });
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.ErrorDefinitionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ErrorDefinitionOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Busbar Lehim Hatası"
                        },
                        new
                        {
                            Id = 2,
                            Label = "Cam Çiziği"
                        },
                        new
                        {
                            Id = 3,
                            Label = "Cam Kirliliği"
                        },
                        new
                        {
                            Id = 4,
                            Label = "Çerçeve Köşe Açıklığı"
                        },
                        new
                        {
                            Id = 5,
                            Label = "Diyot Hatası"
                        },
                        new
                        {
                            Id = 6,
                            Label = "EL hatası"
                        },
                        new
                        {
                            Id = 7,
                            Label = "Etiket Hatası"
                        },
                        new
                        {
                            Id = 8,
                            Label = "EVA Lekesi"
                        },
                        new
                        {
                            Id = 9,
                            Label = "Finger Kırığı"
                        },
                        new
                        {
                            Id = 10,
                            Label = "Gökkuşağı"
                        },
                        new
                        {
                            Id = 11,
                            Label = "Güç Hatası"
                        });
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 10, 11, 51, 3, 285, DateTimeKind.Utc).AddTicks(138),
                            DepartmentId = 5,
                            Email = "admin@sirket.com",
                            Name = "Sistem Yöneticisi",
                            PasswordHash = "$2a$11$eU3sim5JUE2O/lzvlHYNQeKZft0SmZ4m75.YO5lRCet1Wo8xGqYDu",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.UserActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserFullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserActivityLogs");
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.Complaint", b =>
                {
                    b.HasOne("ComplaintsAPI.Domain.Entities.User", "CreatedBy")
                        .WithMany("CreatedComplaints")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComplaintsAPI.Domain.Entities.Department", "CurrentDepartment")
                        .WithMany("Complaints")
                        .HasForeignKey("CurrentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComplaintsAPI.Domain.Entities.User", "ManagementApprovedBy")
                        .WithMany()
                        .HasForeignKey("ManagementApprovedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ComplaintsAPI.Domain.Entities.User", "QualityReportedBy")
                        .WithMany()
                        .HasForeignKey("QualityReportedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("CurrentDepartment");

                    b.Navigation("ManagementApprovedBy");

                    b.Navigation("QualityReportedBy");
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.ComplaintHistory", b =>
                {
                    b.HasOne("ComplaintsAPI.Domain.Entities.User", "ChangedBy")
                        .WithMany("ComplaintHistories")
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComplaintsAPI.Domain.Entities.Complaint", "Complaint")
                        .WithMany("History")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComplaintsAPI.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChangedBy");

                    b.Navigation("Complaint");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.User", b =>
                {
                    b.HasOne("ComplaintsAPI.Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.UserActivityLog", b =>
                {
                    b.HasOne("ComplaintsAPI.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.Complaint", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.Department", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ComplaintsAPI.Domain.Entities.User", b =>
                {
                    b.Navigation("ComplaintHistories");

                    b.Navigation("CreatedComplaints");
                });
#pragma warning restore 612, 618
        }
    }
}
